### ISSUE TITLE
running main errors

### ISSUE THREAD

**Issue by xjdbie96** [AI4Finance-LLC/FinRL-Library#120]
something wrong in input shape
python main.py --mode=train
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 38, in main
    finrl.autotrain.training.train_one()
  File "D:\a_git\FinRL-Library\finrl\autotrain\training.py", line 76, in train_one
    env_train, _ = e_train_gym.get_sb_env()
  File "D:\a_git\FinRL-Library\finrl\env\env_stocktrading.py", line 379, in get_sb_env
    obs = e.reset()
  File "D:\a_git\FinRL-Library\venv\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "D:\a_git\FinRL-Library\venv\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (292,) into shape (301,)

**Comment by rickpm** [comment]
how did you fit it ?

**Comment by impulsecorp** [comment]
Yes, I get that same exact error when running it on my Linux server (Python 3.8):
ubuntu@ip-172-26-7-3:~/FinRL-Library$ python3 main.py --mode=train
/usr/local/lib/python3.8/dist-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  warnings.warn(
==============Start Fetching Data===========
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (156457, 8)
==============Start Feature Engineering===========
Successfully added technical indicators
Successfully added turbulence index
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main()
  File "main.py", line 38, in main
    finrl.autotrain.training.train_one()
  File "/home/ubuntu/FinRL-Library/finrl/autotrain/training.py", line 67, in train_one
    env_train, _ = e_train_gym.get_sb_env()
  File "/home/ubuntu/FinRL-Library/finrl/env/env_stocktrading.py", line 379, in get_sb_env
    obs = e.reset()
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (292,) into shape (301,)

**Comment by peacemind** [comment]
Yes, I get that same exact error when running "python3 main.py --mode=train" on my Ubuntu 20.04 (Python 3.8):
The following show part of the error messages:
/////////////////////
Shape of DataFrame:  (156457, 8)
==============Start Feature Engineering===========
Successfully added technical indicators
Successfully added turbulence index
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main()
  File "main.py", line 38, in main
    finrl.autotrain.training.train_one()
  File "/home/happy/gitprojects/rl/FinRL-Library/finrl/autotrain/training.py", line 67, in train_one
    env_train, _ = e_train_gym.get_sb_env()
  File "/home/happy/gitprojects/rl/FinRL-Library/finrl/env/env_stocktrading.py", line 379, in get_sb_env
    obs = e.reset()
  File "/home/happy/miniconda3/envs/finrl-venv/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/home/happy/miniconda3/envs/finrl-venv/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (292,) into shape (301,)

/////////

**Comment by RomanZWang** [comment]
I'm getting the same error.

**Comment by NeDa-Y** [comment]
same error, even by changing stocks the arrays are different

**Comment by doncat99** [comment]
easy，you need to fill empty dates with data when your select multi stocks. check your dataframeda，group by date，and see if you got equal stocks data for each date
