### ISSUE TITLE
pyfolio

### ISSUE THREAD

**Issue by MightyRaccoon** [AI4Finance-LLC/FinRL-Library#163]
Hi!
I've created virtual env and run command `pip install -r requirements.txt`

After that I run `python main.py --mode train`  and got message `ModuleNotFoundError: No module named 'pyfolio'`

In requirements this module is commented...

**Comment by Mahesha999** [comment]
I uncmomented pyfolio in `requirements.txt` and then installed from `requirement.txt` from as: `pipenv install -r ./requirements.txt` and then ran:

    pipenv install git+https://github.com/AI4Finance-LLC/FinRL-Library.git#egg=finrl

Yup, got pyfolio related error:

```
(stocks) F:\Mahesh\workspaces\stock-trading-with-rl>pipenv install git+https://github.com/AI4Finance-LLC/FinRL-Library.git#egg=finrl
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing git+https://github.com/AI4Finance-LLC/FinRL-Library.git#egg=finrl...
Adding finrl to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock (380fd4) out of date, updating to (87699b)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
 Locking...Building requirements...
Resolving dependencies...
Success!
Updated Pipfile.lock (87699b)!
Installing dependencies from Pipfile.lock (87699b)...
An error occurred while installing git+https://github.com/quantopian/pyfolio.git@4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa#egg=pyfolio-0-9-2! Will try again.
  ================================ 2/2 - 00:01:17
Installing initially failed dependencies...
[InstallError]:   File "f:\programfiles\python\lib\site-packages\pipenv\cli\command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "f:\programfiles\python\lib\site-packages\pipenv\core.py", line 2193, in do_install
[InstallError]:       do_init(
[InstallError]:   File "f:\programfiles\python\lib\site-packages\pipenv\core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "f:\programfiles\python\lib\site-packages\pipenv\core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "f:\programfiles\python\lib\site-packages\pipenv\core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "f:\programfiles\python\lib\site-packages\pipenv\core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting pyfolio-0-9-2
[pipenv.exceptions.InstallError]:   Cloning https://github.com/quantopian/pyfolio.git (to revision 4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa) to c:\users\crrma\appdata\local\temp\pip-install-46_7bb7y\pyfolio-0-9-2_81ee43a050224da0975b619d45f3b654
[pipenv.exceptions.InstallError]: Running command git clone -q https://github.com/quantopian/pyfolio.git 'C:\Users\crrma\AppData\Local\Temp\pip-install-46_7bb7y\pyfolio-0-9-2_81ee43a050224da0975b619d45f3b654'
[pipenv.exceptions.InstallError]:   Running command git rev-parse -q --verify 'sha^4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa'
[pipenv.exceptions.InstallError]:   Running command git fetch -q https://github.com/quantopian/pyfolio.git 4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa
[pipenv.exceptions.InstallError]:   WARNING: Generating metadata for package pyfolio-0-9-2 produced metadata for project name pyfolio. Fix your #egg=pyfolio-0-9-2 fragments.    
[pipenv.exceptions.InstallError]: WARNING: Discarding git+https://github.com/quantopian/pyfolio.git@4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa#egg=pyfolio-0-9-2. Requested pyfolio from git+https://github.com/quantopian/pyfolio.git@4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa#egg=pyfolio-0-9-2 (from -r c:\users\crrma\appdata\local\temp\pipenv-u_ytjm6j-requirements\pipenv-9f04tqxe-requirement.txt (line 1)) has inconsistent name: filename has 'pyfolio-0-9-2', but metadata has 'pyfolio'
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pyfolio-0-9-2 (unavailable)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for pyfolio-0-9-2 (unavailable)
ERROR: Couldn't install package: pyfolio-0-9-2
 Package installation failed...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "F:\ProgramFiles\python\Lib\site-packages\pipenv\vendor\vistir\path.py", line 433, in rmtree
    shutil.rmtree(directory, ignore_errors=ignore_errors, onerror=onerror)
  File "f:\programfiles\python\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "f:\programfiles\python\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "f:\programfiles\python\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "F:\ProgramFiles\python\Lib\site-packages\pipenv\vendor\vistir\path.py", line 528, in handle_remove_readonly
    raise exc_exception
  File "f:\programfiles\python\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\crrma\\AppData\\Local\\Temp\\requirementslib-0netqjx3-src\\finrl'
     ================================ 0/2 - 00:01:20
```

**Comment by Youbadawy** [comment]
@MightyRaccoon, 

`pip install pyfolio `

@XiaoYangLiu-FinRL I believe this issue is resolved, we could now close it...

**Comment by MightyRaccoon** [comment]
@Youbadawy 
I've installed it after I uncommented it. 
But It look a little bit strange. Because I just follow the instructions and get errors)

**Comment by XiaoYangLiu-FinRL** [comment]
pyfolio is a separate module. You can comment it.

**Comment by Mahesha999** [comment]
I got error `AttributeError: 'numpy.int64' object has no attribute ...` while backtesting. It [seems](https://stackoverflow.com/questions/65418898/pyfolio-attributeerror-numpy-int64-object-has-no-attribute-to-pydatetime) that it is known bug. The pypi package seems to be older one. Unistalling it and then installing from github worked: `pipenv install git+https://github.com/quantopian/pyfolio#egg=pyfolio`
