### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by jzamalloa1** [AI4Finance-LLC/FinRL-Library#30]
Hi,

I got the following error when running python main.py --mode=train

==============Start Feature Engineering===========
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    main()
  File "main.py", line 36, in main
    finrl.autotrain.training.train_one()
  File "/mnt/c/Users/JOSE/Documents/PROJECT/STOCK_TRADING/FinRL-Library/finrl/autotrain/training.py", line 30, in train_one
    df = FeatureEngineer(df,
TypeError: __init__() got multiple values for argument 'use_technical_indicator'

I also get this at the beginning of the run:
/mnt/c/Users/JOSE/Documents/PROJECT/STOCK_TRADING/FinRL-Library/venv/lib/python3.8/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.

I installed all dependencies and pre-requisites before running. Can you help me please?

Thanks

**Comment by BruceYanghy** [comment]
I fixed it, please try again. Thanks.

**Comment by jzamalloa1** [comment]
Thanks, I pulled again and after re-running it I got the error below:

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 36, in main
    import finrl.autotrain.training
  File "/mnt/c/Users/XXX/Documents/PROJECT/STOCK_TRADING/FinRL-Library/finrl/autotrain/training.py", line 14, in <module>
    from finrl.env.env_multistock import MultistockEnv
ModuleNotFoundError: No module named 'finrl.env.env_multistock'

**Comment by BruceYanghy** [comment]
It's fixed. I made some improvements early today broke this part again.

**Comment by wjhithit** [comment]
@BruceYanghy pls tell us how to fixed it?
